vich_uploader:
    db_driver: orm

    mappings:
       books:
           uri_prefix: /books
           upload_destination: '%kernel.project_dir%/public/books'
          #  namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           namer: Vich\UploaderBundle\Naming\UniqidNamer
